'use strict';

const fs       = require('fs');
const path     = require('path');
const readline = require('readline');
const chalk    = require('chalk');

const CONFIG_TEMPLATE = (srcDir) => `# ABL Configuration
# Generated by abl init

directories:
  src: ${srcDir}
  # tests and specs live in .abl/ by default
  # override below if needed:
  # tests: ./tests
  # specs: ./specs

models:
  builder: gemini-2.5-pro
  verifier: gemini-2.5-flash

commands:
  health_check: npm run lint && npx tsc --noEmit
  start_dev: npm run dev
  reset_state: npm run db:seed   # remove if stateless
  map_deps: cat package.json

dev_server:
  port: 3000
  ready_endpoint: /api/health
  timeout_ms: 15000

loop:
  max_health_attempts: 10
  max_verifier_iterations: 5
`;

const PROJECT_MD_TEMPLATE = `# Project

Describe your project here. What it does, who it's for, the tech stack,
and any key architectural decisions. This file is read by both the Builder
and Verifier on every run.
`;

const BUILDER_PROMPT_NOTE = `# Note
Prompts live in prompts/builder.md and prompts/verifier.md at project root.
ABL ships with default prompts. Copy them here to customize.
`;

async function initCommand() {
  const cwd = process.cwd();
  const ablDir = path.join(cwd, '.abl');

  if (fs.existsSync(ablDir)) {
    console.log(chalk.yellow('! ABL project already initialized here.'));
    process.exit(0);
  }

  console.log('');
  console.log(chalk.bold('ABL Init'));
  console.log(chalk.dim('Setting up a new ABL project in the current directory.'));
  console.log('');

  const srcDir = await ask('Where is your source directory? (default: ./src): ') || './src';

  // Validate src dir exists
  const srcAbs = path.resolve(cwd, srcDir);
  if (!fs.existsSync(srcAbs)) {
    console.log(chalk.yellow(`! Directory "${srcDir}" does not exist — creating it.`));
    fs.mkdirSync(srcAbs, { recursive: true });
  }

  // Create .abl/ structure
  fs.mkdirSync(ablDir, { recursive: true });
  fs.mkdirSync(path.join(ablDir, 'specs'), { recursive: true });
  fs.mkdirSync(path.join(ablDir, 'tests'), { recursive: true });

  // Write config
  fs.writeFileSync(
    path.join(ablDir, 'abl.config.yaml'),
    CONFIG_TEMPLATE(srcDir)
  );

  // Write project.md
  fs.writeFileSync(
    path.join(ablDir, 'project.md'),
    PROJECT_MD_TEMPLATE
  );

  // Write lean_settings.json
  const leanSettings = JSON.stringify(buildLeanSettings(cwd), null, 2);
  fs.writeFileSync(path.join(ablDir, 'lean_settings.json'), leanSettings);

  // Write geminiignore.txt
  fs.writeFileSync(
    path.join(ablDir, 'geminiignore.txt'),
    buildGeminiIgnore(srcDir)
  );

  // Write specs/index.md placeholder
  fs.writeFileSync(
    path.join(ablDir, 'specs', 'index.md'),
    '# Specs Index\n'
  );

  // Create logs dir
  fs.mkdirSync(path.join(cwd, 'logs'), { recursive: true });
  fs.writeFileSync(
    path.join(cwd, 'logs', '.gitkeep'),
    ''
  );

  // Write .gitignore additions
  const gitignorePath = path.join(cwd, '.gitignore');
  const gitignoreAdditions = '\n# ABL\nlogs/*\n!logs/tokens.csv\n';
  if (fs.existsSync(gitignorePath)) {
    const existing = fs.readFileSync(gitignorePath, 'utf8');
    if (!existing.includes('# ABL')) {
      fs.appendFileSync(gitignorePath, gitignoreAdditions);
    }
  } else {
    fs.writeFileSync(gitignorePath, gitignoreAdditions.trim() + '\n');
  }

  console.log('');
  console.log(chalk.green('✓ ABL project initialized'));
  console.log('');
  console.log('  Next steps:');
  console.log(chalk.dim(`  1. Edit .abl/project.md — describe your project`));
  console.log(chalk.dim(`  2. Write your first spec in .abl/specs/phase1.md`));
  console.log(chalk.dim(`  3. Add GEMINI_API_KEY=your_key to .env`));
  console.log(chalk.dim(`  4. Run: abl phase 1`));
  console.log('');
}

function ask(question) {
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  return new Promise(resolve => {
    rl.question(question, answer => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function buildLeanSettings(projectRoot) {
  return {
    general: { defaultApprovalMode: 'yolo', checkpointing: { enabled: true } },
    model: { disableLoopDetection: true, maxSessionTurns: 50, compressionThreshold: 0.8 },
    modelConfigs: {
      customAliases: {
        'chat-compression-default':    { modelConfig: { model: 'gemini-2.5-flash-lite' } },
        'loop-detection-double-check': { modelConfig: { model: 'gemini-2.5-flash-lite' } },
        'summarizer-default':          { modelConfig: { model: 'gemini-2.5-flash-lite' } },
        'summarizer-shell':            { modelConfig: { model: 'gemini-2.5-flash-lite' } },
        'classifier':                  { modelConfig: { model: 'gemini-2.5-flash-lite' } },
        'prompt-completion':           { modelConfig: { model: 'gemini-2.5-flash-lite' } },
      }
    },
    context: {
      fileName: [],
      includeDirectoryTree: false,
      discoveryMaxDirs: 0,
      loadMemoryFromIncludeDirectories: false,
      fileFiltering: {
        respectGitIgnore: true,
        respectGeminiIgnore: true,
        customIgnoreFilePaths: [ path.join(projectRoot, '.abl', 'geminiignore.txt') ],
      }
    },
    tools: {
      truncateToolOutputThreshold: 2500,
      disableLLMCorrection: true,
      shell: { enableShellOutputEfficiency: true }
    },
    experimental: {
      toolOutputMasking: { enabled: true, toolProtectionThreshold: 5000, minPrunableTokensThreshold: 5000 },
      jitContext: false,
    }
  };
}

function buildGeminiIgnore(srcDir) {
  return `# Block everything by default
/*

# Allow only ABL-relevant directories
!${srcDir}/
!/.abl/specs/
!/.abl/tests/

# Block heavy junk
**/node_modules/
**/package-lock.json
**/.next/
**/dist/
**/build/
**/.git/
**/*.svg
**/*.ico
**/*.png
**/*.jpg
**/*.jpeg
**/*.tsbuildinfo
**/*.map
**/*.lock

# Block ABL internals — piped manually by ABL
/prompts/
/logs/
/.abl/project_map.txt
/.abl/project.md
/.abl/lean_settings.json
/.abl/geminiignore.txt
/Makefile
/.env
`;
}

module.exports = initCommand;